name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to EC2
        run: |
          # Remove previous files on EC2
          ssh -i id_rsa.pem ec2-user@34.242.206.146 "rm -rf /var/www/html/*"

          # Upload new files to EC2
          scp -i id_rsa.pem -r TotalCareFixWeb/* ec2-user@34.242.206.146:/var/www/html/

          # Provide URL to access the deployed website
          echo "Website deployed. Access it at: http://34.242.206.146/"
