name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy code to EC2
        uses: appleboy/scp-action@master
        with:
          host: 34.242.206.146
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "." # Use the current directory (repository root) as the source
          target: "/web" # Path on the EC2 instance to deploy the files
          debug: true # Enable debug mode

      - name: SSH into EC2 and run script
        uses: appleboy/ssh-action@master
        with:
          host: 34.242.206.146
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /web
            # Run any setup commands or commands to start your application
            # For example, if you're using a simple server like http-server:
            npm install -g http-server
            npm start
