name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Delete old project
        uses: appleboy/ssh-action@master
        with:
          host: 34.242.206.146
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -r TotalCareFixWeb &
            echo "Old repo deleted."
      - name: Cloning repo to EC2
        uses: appleboy/scp-action@master
        with:
          host: 34.242.206.146
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git clone https://github.com/NishantTaletiyaJain/TotalCareFixWeb.git
            cd TotalCareFixWeb
            http-server
