name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 34.242.206.146
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            rm -rf TotalCareFixWeb
            git clone https://github.com/NishantTaletiyaJain/TotalCareFixWeb.git
            cd TotalCareFixWeb
            nohup http-server &
            echo "Server started."
